apiVersion: v1
kind: Service
metadata:
  name: fmtok8s-monolith
spec:
  type: NodePort
  selector:
    app:  monolith
  ports:
    - port: 80           # The port exposed by the service
      targetPort: 80     # The port your app container listens on
      protocol: TCP
      nodePort: 30081  
