apiVersion: v1
kind: Service
metadata:
  name: fmtok8s-monolith
spec:
  type: NodePort
  selector:
    app: monolith
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30081
